### PR TITLE
Update screenshot.png

### PR DESCRIPTION
**Pull request by AwesomestCode**

### CODE REVIEW

**Comment by rom1504** [comment]
Can you compress it a bit more ? 3MB is really big

**Comment by AwesomestCode** [comment]
> Can you compress it a bit more ? 3MB is really big

@rom1504: How can I compress it? I don't think I can use archives to display images on GitHub.

**Comment by rom1504** [comment]
I mean re-encode the image.
You can do it in any image edition software

**Review by rom1504 — APPROVED** [review]

**Comment by rom1504** [comment]
let's merge

this will probably be removed when we have tests similar to pviewer anyway

**Pull request merged**
