### PR TITLE
Added 2DCanvas GUI

### PR DESCRIPTION
**Pull request by KalmeMarq**

### CODE REVIEW

**Comment by rom1504** [comment]
That's a lot of code.

Did you write this for this feature or some of it is copied from somewhere else ?

**Comment by KalmeMarq** [comment]
I have a MC TS project. I remake the Java GUI on the browser with typescript but here I needed to convert it to JS.

**Comment by rom1504** [comment]
This is too much code for this project imo. It would make it hard to maintain.
There are 2 solutions to this:
1. Keep only the part of the code that is needed for this feature
2. Publish your project as a npm package and use it here : that would decrease the amount of code we have here

**Comment by KalmeMarq** [comment]
All the code there is needed. How do I do 2.?

**Comment by rom1504** [comment]
Create a GitHub repo (you can press use this template https://github.com/PrismarineJS/prismarine-template for structure), then expose your classes with module.exports then publish on npm
Then you will be able to add it to our package.json and require it.
Feel free to ask if you have more questions

**Comment by rom1504** [comment]
You could call it minecraft-menu-gui or anything you like. It would provide ways to render minecraft-like menus. Could be used here but also in other projects

**Comment by rom1504** [comment]
I think it would also help if you could describe (in english) all the changes you made and the features you implemented. Looking at the code it seems to be a lot

**Comment by KalmeMarq** [comment]
Describe it on the commit desc? I think it has a limit of words and there's a lot to say.

**Comment by rom1504** [comment]
Ah I see you have this repo https://github.com/KalmeMarq/Minecraft-TS

Mostly about finding good ways to expose this then.

One of the core objective of prismarine-web-client is to put all the large features in modules (like rendering the 3d world in pviewer, talking to the server in mineflayer, and inventory in another module), so that the app itself says light.

So it would be useful to identify what component you are bringing (I think it's menus ?) And try to expose that on your side and only use that here.

**Comment by rom1504** [comment]
You can describe it here in comments /pr description

**Comment by KalmeMarq** [comment]
About the module.exports, it's like this?
image

**Comment by rom1504** [comment]
Yes

You can also choose to use es6 exports

**Comment by rom1504** [comment]
https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export

**Comment by Karang** [comment]
First thing to do to reduce the size of this PR: all the textures are already provided by mcAssets, so you don't need to add them again in extra-textures. For instance https://webclient.prismarine.js.org/textures/1.16.4/gui/checkbox.png

**Comment by rom1504** [comment]
I'd like to avoid having ton of code in this project (otherwise what happens is people fork us instead of reusing), but I also understand it's hard to expose the code / make it not completely specific.

After some discussions with @KalmeMarq he's not sure how do the packaging so I'll have a longer look at this later and describe how we can integrate this in a good way.

**Review by KalmeMarq — COMMENTED** [review]
-ResourceLoadinGui. When reloading resources this Gui will show up above all.
-MainMenuScreen. Includes the random splash text, 'minecarft' easter egg and fade animation. The 'Show Form' button will go to ConnectScreen and remove the panoramas.
-ConnectScreen. Shows the 'prismarine-menu' plus two buttons on the bottom. 'Connect' (the same as 'Play') and 'Cancel' (goes back to the main screen) and readds the panoramas.
-OptionsScreen. Only has one option (Hide GUI) for now.
-World Loading. Replaces the loading-menu. When bot is disconnected a button will appear to go back to the main screen (not yet working).
-IngameMenu (pause screen). On 'esc' it shows up and to close it and go back to game there is a 'Return to Game' button. It can access the OptionsScreen and has a 'Disconnect' button which is not fully working yet.
-IngameGui. Renders the bot health, food, experience (not fully working yet) and the hotbar (not yet complete). Pressing 'F3' it shows the DebugOverlayGui (not yet complete) and pressing 'F1' it hides/shows the Gui.
-Pressing 'F2' will take a screenshot of the canvas. (TODO: Capture the world canvas too and put them together).
-Changing the selected hotbar slot only works if you are inside of a world and if there's no screen being rendering (Only showing the IngameGui).
-Pressing Tab will focus the widgets like tabindex in html.
-Pressing Enter clicks the buttons.
-Bot render distance uses gameSettings renderDistance option. Slider Option not yet implemented.
-Added PlayerBot. It stores the bot and some of its attributes for easier use in screens.
-debug-menu removed.
-loading-menu removed.
-crosshair removed. It's now rendered in IngameGui (which fixes zIndex).
-playerlist and chatbox only show when the world is fully loaded. It was appearing immedialety after 'Play' button being clicked.
-Clicking in the screen to pointerlock the renderer only works the first time. After that only being clicking the 'Return to Game' button in IngameMenu (TODO: Close it with 'Escape' too).
-remove code for changing hotbar selected item on the hotbar element and inside the connect function. It's now inside the KeyboardListener and MouseHelper. (TODO: Use keybindings)
-remove function to update the bot health, food and saturation. It's now done in PlayerBot.

Utils/...

-GameOption. Contains all options functionality.

GameSettings
-Contains the game options.
-loadOptions(). Gets the options from localStorage and use them.
-saveOptions(). Saves the changed options to localStorage.

Context2D
-setContext(context). Sets the context which Context2D will draw in.
-clear(). clearRect() the current context.
-setup(scale, isPixelated). Sets the scale using setTransform and sets the imageSmoothingEnabled.
-setTranform(scaleh, a, b, scalev, c, d). setTransform the current context.
-fillRect(x, y, width, height, color). fillRect the current context (Not yet using decimal values for color because the ColorHelper isn't working properly).
-drawImage(uvX, uvY, uvSizeX, uvSizeY, x, y, width, height). drawImage on the current context if image is already loaded.
-bindImage(source). Sets which image will be use in drawImage()
-compositionMode(mode). Change globalCompositionOperation. Use 'reset' to go back to the default mode.
-setAlpha(alpha). Set current context global alpha.
-createTilePattern(...). Draw a tile pattern (not 100% accurate).
-block(callback). Use context functions inside save() and restore().
-rotateScale(angle, x, y, scale). Rotates in the center provided.
-drawText(text, x, y, color?, shadow?). Draws text. It's deprecated bc it was only to be use when forceUnicodeFont is enabled but the FontRenderer is not implemented.

TextureManager
-reload(). Clears the images stored. (TODO: Load preloaded images here);
-bindImage(resource). If the image is already loaded and stored it will call Context2D.bindImage(resource) otherwise it will call loadImage(resource).
-loadImage(resource). Fetches the image and stores it. 
-getImagesMap(). Retuns the store images object.
-getTexture(resource). Retuns the source of the image specified.

ClipBoard
-getClipboard(). Returns the user clipboard content if allowed.
-copyToClipboard(content). Sends content to user clipboard.
-setClipboardString(string). Check if it's possible to work with the user clipboard and if so it calls copyToClipboard().

...

**Comment by rom1504** [comment]
Hi a few questions
* Does this work on mobile (do you adapt to other resolutions ?) ?
* you need to rebase on master

**Comment by rom1504** [comment]
I can see a lot of magic values there https://github.com/PrismarineJS/prismarine-web-client/pull/125/files#diff-f576099551119494e523ce544ebbb638768af1d11c4e946bec2bf06cf8eb5c80R89 how did you compute them ?

**Comment by extremeheat** [comment]
Reviewed your code and it seems like you ported the MC source over to JS. On Mojang's side they don't have a layout system like HTML so it makes sense for them to have to reimplement things like overlays, mouse events, input events, etc manually. So by copying the MC code what you're doing is effectively writing your own layout and event system instead of using the existing one in the browser, so I'm curious why you think this is better?

Some comments:

* What benefits does this have over using the existing system in the browser?
* What do you think the performance impact will be for the draw code over letting the browser handle it? Usually canvas is good for custom draw steps like animations or heavy changes to the screen layout as dom manipulation can be slow. However if you don't update the screen alot, that can unnecessarily block other things unless you have logic to only render when something changed on the screen.
* Maintainability to me seems to be worse compared to HTML, what do you think ? I think writing a layout system would simplify things, like [here](https://github.com/extremeheat/minecraft-inventory-gui/blob/master/lib/layouts.mjs), no need for heavy OOP in js
* Responsive UI will be more complicated, for example supporting mobile or other devices where you could normally just do CSS media queries, how do you plan to deal with these devices?

**Comment by rom1504** [comment]
Thanks for the work you've been doing @KalmeMarq !
I think it's pretty interesting to recode minecraft in a java-style with canvas, and I think you could probably continue this work in your repo, and build some kind of bridge with this project (for example you could depend on this project and use it, or make your ui some kind of plugin)

However, this is not the direction we want to take here.
The main reason for this is we'd like to keep the code as light as possible to make it easier to maintain and improve. It seems using html make this possible.

The feature this PR are bringing are the following:
* settings menu (#67 )
* healh bar (#85 )
* sensitivity slider (#28 )

We believe it would be possible to implement these features with less code in html, so we're going to take this direction.

If you want to try your hand at implementing these features in html/css, you are welcome to.
It's also ok if you don't.

Feel free to keep sharing any new work you do on this in our discord.

I'll be closing this now, thanks.

**Pull request closed without merging**
