### PR TITLE
Added docker ci

### PR DESCRIPTION
**Pull request by dada513**
someone with admin permissions has to set some github project variables, flying squid repo has those and the repo has to have GitHub Container Registry enabled too

### CODE REVIEW

**Comment by dada513** [comment]
I also fixed the docker error. Because the config was now copied by webpack, if it was in dockerignore build would fail. I made the docker image delete the config.json after build (so that a new one can be mounted, and the preffered config by express is the top one)

**Comment by dada513** [comment]
I also made a little change that disabled using spaces in usernames, I dont think a new PR for that is needed

**Comment by rom1504** [comment]
@dada513 added the missing secrets

it seems this job will never trigger (nothing in on:), did you mean to put something there?

**Comment by dada513** [comment]
> @dada513 I added the missing secrets
> 
> it seems this job will never trigger (nothing in on:), did you mean to put something there?

That was an err, should be fixed

**Review by rom1504 — APPROVED** [review]

**Comment by rom1504** [comment]
it didn't work https://github.com/PrismarineJS/prismarine-web-client/actions/runs/699256982
probably missing some things

can you re-open the PR ?

**Pull request merged**
