### PR TITLE
Avoid copy of unchanged files

### LINKED ISSUE #210: Make Webpack faster
We're at this point again. Somehow, webpack is again being extremely slow. This is hampering development; I can't iterate quickly/test stuff if I need to wait a minute every time I make a change, no matter how small.

### PR DESCRIPTION
**Pull request by Saiv46**
It uses modified time of source and destination files (if exists) to filter out unchanged files from being copied on build.

Closes #210

### CODE REVIEW

**Comment by Saiv46** [comment]
```
Module not found: Error: Can't resolve 'tls' in '/home/runner/work/prismarine-web-client/prismarine-web-client/node_modules/https-proxy-agent/dist'
```

The fuck? How my PRs broke other webpack plugins in unexpected ways?

**Comment by rom1504** [comment]
I fixed the tls issue

**Comment by rom1504** [comment]
@KalmeMarq @AwesomestCode can you check if this works for you?

Things that should work:
* npm start
* npm run build

**Comment by Saiv46** [comment]
I still can't get build work with PNPM, while NPM installing packages *slower* on my new SSD

**Comment by AwesomestCode** [comment]
Quickly checked on GitPod. It compiles successfully though some assets seem to be missing? Or my computer might just be weird.
Screenshot 2022-03-08 at 15 56 33

**Comment by Saiv46** [comment]
Closed in favor of #253

**Pull request closed without merging**
