### PR TITLE
Implement auth

### PR DESCRIPTION
**Pull request by sverben**
This enables online mode using a chrome extension
[Extension](https://github.com/sverben/MSMC-Chrome)

Possible enhancements: 
 - Add a button on the play_screen component to display where to download the extension
 - Upload to Chrome Web Store

### CODE REVIEW

**Comment by sverben** [comment]
This closes #251 and #27

**Comment by rom1504** [comment]
interesting solution.
Could someone try it ? maybe @AwesomestCode ?

**Comment by IlanLuci** [comment]
Doesn't seem to be working on 1.8.9 and potentially other versions as well. When I try to join minemen.club or hypixel i get "RangeError: Invalid WebSocket frame: RSV1 must be clear" referencing events.js:377
      throw er; // Unhandled 'error' event -- not sure if this is something on my end or a problem for others as well. I'm on a mac testing on brave browser. I am going to install chrome rn and see if its a problem there too.

**Comment by rom1504** [comment]
seems it doesn't work so let's not merge

**Pull request closed without merging**
