### PR TITLE
fix ctrl-w

### PR DESCRIPTION
**Pull request by host008**

### CODE REVIEW

**Comment by rom1504** [comment]
Seems like that would prevent users to close the tab ?

**Comment by host008** [comment]
yes

**Comment by rom1504** [comment]
How can they close the tab then?

**Comment by host008** [comment]
esc - left click on tab - close tab

**Comment by rom1504** [comment]
Can you run npm run fix for lint ?

**Comment by host008** [comment]
how?

**Comment by host008** [comment]
I forgot

**Comment by rom1504** [comment]
`npm run fix` in your terminal

**Comment by host008** [comment]
k done

**Comment by rom1504** [comment]
I just tested this, it doesn't prevent ctrl+w from closing the tab

**Comment by host008** [comment]
oh lemme try again

**Review by AwesomestCode — CHANGES_REQUESTED** [review]
Let's not force people to install an extension; they might as well install our PWA if they're doing that.

Also, please don't put JS directly into the HTML.

**Comment by host008** [comment]
ok.

**Comment by host008** [comment]
Done!
😃

**Comment by rom1504** [comment]
Making people install an extension just to avoid Ctrl+w closing the tab isn't a good solution

**Comment by host008** [comment]
ok

**Comment by rom1504** [comment]
#117 is not waiting for an implementation, it's waiting for an idea
nobody has an idea yet

**Comment by host008** [comment]
done

**Pull request closed without merging**
