### PR TITLE
Added block name and properties to debug menu, also hp and food till #85 is done

### PR DESCRIPTION
**Pull request by Moondarker**
image

### CODE REVIEW

**Review by Karang — APPROVED** [review]
Nice

**Review by rom1504 — COMMENTED** [review]
Can we *not* use customEntries for not custom entries ?

Just add that directly in the debug menu

**Comment by Karang** [comment]
> Can we _not_ use customEntries for not custom entries ?
> 
> Just add that directly in the debug menu

As he explained in the PR, those values are temporary in debug until we make the ui for it. I think it makes sense to have them in custom entries, for easy removal.

**Comment by rom1504** [comment]
ok

**Pull request merged**
