### PR TITLE
Hit entities

### PR DESCRIPTION
**Pull request by KalmeMarq**

### CODE REVIEW

**Review by AwesomestCode — APPROVED** [review]
Code LGTM

CI failing

**Comment by KalmeMarq** [comment]
image
idk how to fix it. Idu why it even came up. It's like the other time when two modules were also missing.

**Comment by rom1504** [comment]
looks like something that is broken unrelated to this PR, but it still needs to be fixed (that can be done in another PR)

**Comment by rom1504** [comment]
I would just add tls to the list of fallback

**Comment by rom1504** [comment]
I fixed the tls issue

**Comment by KalmeMarq** [comment]
now idk how to put yours changes on mine

**Comment by KalmeMarq** [comment]
wait it works now. nice

**Pull request merged**
