### PR TITLE
Update login menu

### PR DESCRIPTION
**Pull request by KalmeMarq**
Different scales:
image
image
image

Readded subtitle.
Fixed font size and spaces.
Rearranged link buttons.

### CODE REVIEW

**Comment by rom1504** [comment]
I think there should be some padding in input.

You also need to rebase on master and `npm run fix`

**Comment by KalmeMarq** [comment]
padding in the input?

**Comment by KalmeMarq** [comment]
> padding in the input?

this?
image

**Comment by KalmeMarq** [comment]
I'm not sure what rebase on master is.

**Comment by rom1504** [comment]
git remote add upstream https://github.com/PrismarineJS/prismarine-web-client.git
git fetch upstream
git rebase upstream/master
git push --force origin update-login-menu

**Comment by rom1504** [comment]
This still need lint fixing (`npm run fix`)

**Comment by KalmeMarq** [comment]
I did npm run fix. but I'll do once again then.

**Comment by rom1504** [comment]
before
image

after
image

**Comment by rom1504** [comment]
minecraft looks like this:
image

**Comment by AwesomestCode** [comment]
> minecraft looks like this:
I think that's mainly an issue of whether we want to make this look closer to the in game menu or the launcher menu. I think in game is better, unless we want multiple screens.

**Comment by KalmeMarq** [comment]
That's the launcher. Not minecraft.

**Comment by rom1504** [comment]
That's the first screen players see

**Comment by KalmeMarq** [comment]
On the launcher. Not the game. Bc you also have mc dugeons that has a completely different gui.

**Comment by rom1504** [comment]
image

I tried unzooming (75%) and it looks like this, slightly better

**Comment by KalmeMarq** [comment]
So small '-'

**Comment by rom1504** [comment]
Ok I think there's not a lot of reason not to merge this.
Please comment here if you see any reason @Karang @u9g @AwesomestCode

**Comment by AwesomestCode** [comment]
Reasons to merge: makes it more obvious this is for Minecraft.
Personally I'm mildly peeved by BadLion client's non-Minecrafty UI; wonder if other people think that about this client.

**Pull request merged**
