### PR TITLE
Update prismarine-menu

### PR DESCRIPTION
**Pull request by KalmeMarq**
Added widgets image and updated the menu to look like MC Java.

### CODE REVIEW

**Comment by rom1504** [comment]
Isn't that widgets image present in minecraft assets ?

Can you post here the screenshot of how it now looks like ?

**Comment by KalmeMarq** [comment]
It's not in the assets folder.
image

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/minecraft-assets/blob/master/data/1.16.4/gui/widgets.png

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/prismarine-web-client/blob/master/lib/hotbar.js#L154

**Comment by rom1504** [comment]
merged in other pr

**Pull request closed without merging**
