### PR TITLE
Update login menu

### PR DESCRIPTION
**Pull request by KalmeMarq**
Added button, buttonlink and text field components using lit elements.
Updated login menu.

### CODE REVIEW

**Comment by rom1504** [comment]
Can you use the image from minecraft assets ? I showed how in comments of the other PR

**Comment by rom1504** [comment]
Can you run npm run fix to fix linting issue ?

**Comment by rom1504** [comment]
Does this work on mobile ?

**Comment by KalmeMarq** [comment]
I thought you said to add stuff one at a time. The function for gui scale factor would be another pr. And I'm using the minecraft assets textures. I just forgot to delete the image once again.

**Comment by rom1504** [comment]
If this doesn't break mobile it's ok. Is it broken on mobile after that ?

**Comment by KalmeMarq** [comment]
> If this doesn't break mobile it's ok. Is it broken on mobile after that ?

Now it calculates the scale factor so it'll always adjust to the device/window size.

**Review by rom1504 — APPROVED** [review]

**Comment by rom1504** [comment]
please reopen and retry

**Pull request merged**
