### PR TITLE
UI reorganized and options

### PR DESCRIPTION
**Pull request by KalmeMarq**
UI files reorganized, added 1.18 panorama (using boxgeo), added some keybinds, added options to settings screen (mouse sensitivity x/y, chat width/height, sound (ui), render distance, fov and gui scale sliders), added food and xp bars and more debug info (dimension, biome, day, light, number of entities) and playerlist will have columns of 10 players each.

### CODE REVIEW

**Comment by rom1504** [comment]
big code change but overall it looks ok

anyone want to try it out to make sure everything works?

**Comment by extremeheat** [comment]
Tested some basic use and it seems to work pretty well, 👍

There are some regressions on mobile but I don't think that was a big priority. Looks like the test server is also broken.

**Comment by rom1504** [comment]
Let's go

**Comment by rom1504** [comment]
CI failed https://github.com/PrismarineJS/prismarine-web-client/runs/4626600275?check_suite_focus=true

Can you have a look @KalmeMarq ?

**Comment by KalmeMarq** [comment]
sure. I'll see what's going on.

**Comment by KalmeMarq** [comment]
rom, I think we have a problem. because "npm run build" works for me.

**Comment by KalmeMarq** [comment]
In that terminal it mentions that a node_modules was not found. Maybe that's the reason.

**Comment by rom1504** [comment]
@KalmeMarq can you retry the same using the current master branch?
I think you're missing some recent commits in your local setup

**Comment by KalmeMarq** [comment]
I'm using the master branch and with it I did "git fetch upstream", "git merge upstream/master master" and "git rebase upstream/master". It works.

**Comment by KalmeMarq** [comment]
I deleted node_modules and run "npm install" && "npm run build". Now I got the same log as you. I'm using v17.2.0. I don't know if the node version is the issue.

**Comment by rom1504** [comment]
I doubt it's a node version issue
CI is using node 14

**Comment by KalmeMarq** [comment]
I'm going to run "npm run build" again. If it gets the same issue. I'll redo the "npm i" and build. Failing again I'll add the --ignore-engines flag when doing "npm i". If the build works then I think it's the node version. (if this logic makes sense :/)

**Comment by rom1504** [comment]
I think there is an issue with either package.json either webpack config. It should be fixed
The first run of npm install && npm run build from a new environment need to work.
Rerunning thèse commands multiple times is not a solution

**Comment by KalmeMarq** [comment]
package.json wasn't changed nor webpack config

**Comment by KalmeMarq** [comment]
the "url" and "querystring" modules aren't being installed with "npm i"

**Comment by KalmeMarq** [comment]
when I install them manually it finally works. This is now something I don't know any about.

**Comment by rom1504** [comment]
Probably add them in package.json then
This might have been caused by updates in dependencies

**Pull request merged**
